syntax = "base16-ocean.dark"

[ui]
content_bg = "#202020"
scrollbar_hover = "#FFFFFF"
status_bg = "#353535"
status_brand_bg = "#353535"
status_brand_fg = "#F0AF00"
status_error_bg = "#353535"
status_error_fg = "#EE4A59"
status_filename_bg = "#353535"
status_filename_fg = "#95C5FF"
status_percent_fg = "#FFB7B7"
status_reloaded_bg = "#353535"
status_reloaded_fg = "#B3F6C0"
status_search_bg = "#353535"
status_search_fg = "#C0C0C0"
status_separator = "#FFFFFF"
status_shortcut_fg = "#DF50B0"
status_success_bg = "#353535"
status_success_fg = "#B3F6C0"
status_warning_fg = "#FF8900"
status_watch_bg = "#353535"
status_watch_fg = "#F0DF33"
toc_accent = "#FFA6FF"
toc_active_bg = "#264F60"
toc_bg = "#353535"
toc_border = "#FFFFFF"
toc_header_fg = "#C0C0C0"
toc_inactive_bg = "#353535"
toc_index_inactive = "#FFB7B7"
toc_primary_active = "#C0C0C0"
toc_primary_inactive = "#C0C0C0"
toc_secondary_inactive = "#C0C0C0"
toc_secondary_text_active = "#C0C0C0"
toc_secondary_text_inactive = "#C0C0C0"

[markdown]
alert_caution = "#EE4A59"
alert_important = "#22FF22"
alert_note = "#FFB7B7"
alert_tip = "#D5508F"
alert_warning = "#FF8900"
blockquote_marker = "#FF4090"
blockquote_text = "#808080"
code_frame = "#95C5FF"
code_gutter = "#95C5FF"
code_label = "#FFA6FF"
heading_1 = "#EE4A59"
heading_2 = "#FF8900"
heading_3 = "#F0DF33"
heading_4 = "#70D533"
heading_other = "#33DBC3"
heading_underline = "#FFFFFF"
inline_code_fg = "#95C5FF"
latex_block_fg = "#FFB7B7"
latex_inline_fg = "#FFB7B7"
link_hover = "#2BFF99"
link_icon = "#FF4090"
link_text = "#FF4090"
list_level_1 = "#FF4090"
list_level_2 = "#FF4090"
list_level_3 = "#FF4090"
mark_bg = "#C0C0C0"
mark_fg = "#202020"
mermaid_arrow = "#FFFFFF"
mermaid_block_fg = "#C0C0C0"
mermaid_keyword = "#60AFFF"
mermaid_label = "#FFA6FF"
ordered_list = "#FF4090"
rule = "#808080"
search_highlight_bg = "#353535"
search_match_bg = "#264F60"
strong_text = "#C0C0C0"
table_border = "#FFFFFF"
table_cell = "#C0C0C0"
table_header = "#C0C0C0"
table_separator = "#FFFFFF"
task_checked = "#FF4090"
text = "#C0C0C0"
