[settings]
experimental = true
lockfile = true

[tools]
lefthook = "2"
stylua = "2"

[tasks.lefthook-install]
run = "lefthook check-install || lefthook install"

[[hooks.enter]]
script = "mise install --locked"

[[hooks.enter]]
task = "lefthook-install"

[[watch_files]]
patterns = ["mise.toml"]
run = "mise install"

[[watch_files]]
patterns = ["lefthook.yml"]
task = "lefthook-install"
