{ ... }:
{
  imports = [ ];

  programs.git-cliff.settings.changelog = {
    trim = true; # remove the leading and trailing whitespace from the templates
    header = "# Changelog\n\n"; # top-level text

    # https://keats.github.io/tera/docs/#introduction
    body =
      let
        version = # jinja
          ''
            ## [{{ version }}] - {{ timestamp | date(format="%Y-%m-%d") }}
          '';

        unreleased = # jinja
          ''
            ## [unreleased]
          '';

        commits = # jinja
          ''
            {%- for commit in commits %}
              {%- if commit.scope -%}
              {% else -%}
                - {{ commit.message | upper_first }}
                {% if commit.breaking -%}
                {% raw %}  {% endraw %}- **BREAKING**: {{commit.breaking_description}}
                {% endif -%}
              {% endif -%}
            {% endfor -%}
          '';

        groups = # jinja
          ''
            {% for group, commits in commits | group_by(attribute="group") %}
              ### {{ group | upper_first }}
              {% for commit in commits
              | filter(attribute="scope")
              | sort(attribute="scope") %}
                - *({{commit.scope}})* {{ commit.message | upper_first }}
                {%- if commit.breaking %}
                {% raw %}  {% endraw %}- **BREAKING**: {{commit.breaking_description}}
                {%- endif -%}
              {%- endfor -%}
              {% raw %}''\n{% endraw %}
              ${commits}
            {% endfor %}
          '';
      in
      # jinja
      ''
        {% if version %}${version}{% else %}${unreleased}{% endif %}${groups}
      '';

    # template for the changelog footer
    footer = # jinja
      ''
        {% for release in releases -%}
          {% if release.version -%}
            {% if release.previous.version -%}
              [{{ release.version }}]: https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/compare/{{ release.previous.version }}..{{ release.version }}
            {% endif -%}
          {% else -%}
            [unreleased]: https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/compare/{{ release.previous.version }}..HEAD
          {% endif -%}
        {% endfor %}

        <!-- generated by git-cliff -->
      '';
  };
}
