{ inputs, outputs, config, lib, pkgs, ... }:
let
	util = outputs.lib;
	inherit (util.strings) multiline;
in {
	imports = [];

	programs.librewolf.settings = lib.mapAttrs' (n: lib.nameValuePair "userChrome.${n}") {
		"compatibility.os" = true;
		"compatibility.theme" = true;
		"decoration.animate" = true;
		"decoration.cursor" = true;
		"decoration.download_panel" = true;
		"decoration.field_border" = true;
		"fullscreen.overlap" = true;
		"fullscreen.show_bookmarkbar" = true;
		"icon.1-25px_stroke" = true;
		"icon.context_menu" = true;
		"icon.global_menu" = true;
		"icon.global_menubar" = true;
		"icon.library" = true;
		"icon.menu" = true;
		"icon.panel" = true;
		"icon.panel_full" = true;
		"icon.panel_photon" = false;
		"icon.panel_sparse" = false;
		"padding.bookmark_menu" = true;
		"padding.bookmarkbar" = true;
		"padding.global_menubar" = true;
		"padding.infobar" = true;
		"padding.menu" = true;
		"padding.navbar_width" = true;
		"padding.panel" = true;
		"padding.popup_panel" = true;
		"padding.tabbar_height" = true;
		"padding.tabbar_width" = true;
		"padding.toolbar_button" = true;
		"padding.urlbar" = true;
		"rounding.square_tab" = false;
		"tab.bar_separator" = false;
		"tab.bottom_rounded_corner" = true;
		"tab.box_shadow" = true;
		"tab.close_button_at_hover" = true;
		"tab.color_like_toolbar" = true;
		"tab.connect_to_window" = true;
		"tab.container" = true;
		"tab.crashed" = true;
		"tab.dynamic_separator" = true;
		"tab.dynamic_separtor" = true;
		"tab.lepton_like_padding" = true;
		"tab.letters_cleary" = true;
		"tab.multi_selected" = true;
		"tab.newtab_button_like_tab" = true;
		"tab.newtab_button_proton" = false;
		"tab.newtab_button_smaller" = false;
		"tab.photon_like_contextline" = false;
		"tab.photon_like_padding" = false;
		"tab.pip" = true;
		"tab.sound_hide_label" = true;
		"tab.sound_with_favicons" = true;
		"tab.static_separator" = false;
		"tab.static_separator.selected_accent" = false;
		"tab.unloaded" = true;
		"theme.built_in_contrast" = true;
		"theme.fully_color" = true;
		"theme.fully_dark" = true;
		"theme.proton_chrome" = true;
		"theme.proton_color" = true;
		"theme.system_default" = true;
	};
}
