require("plugins.pack.mini.ai")
require("plugins.pack.mini.align")
require("plugins.pack.mini.files")
require("plugins.pack.mini.git")
require("plugins.pack.mini.icons")
require("plugins.pack.mini.misc")
require("plugins.pack.mini.move")
require("plugins.pack.mini.notify")
require("plugins.pack.mini.operators")
require("plugins.pack.mini.sessions")
require("plugins.pack.mini.splitjoin")
require("plugins.pack.mini.surround")
-- require("plugins.pack.mini.tabline")
require("plugins.pack.mini.trailspace")
